language: node_js
node_js:
    - "18.14.0"
    - "20"
    - "22"
dist: focal
addons:
  apt:
    packages:
      # This is required to run puppeteer (chrome) on linux
      - libnss3
      # for screenshot comparison
      - graphicsmagick
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test-all
